### ISSUE TITLE
JoomGallery Author linked to CB profile

### ISSUE THREAD

**Issue by line49** [JoomGallery/jg-cb-tab#1]
Hi,

We have a Joomla 3.3.1 site with the JoomGallery 3.1.1, and CB 1.9.1 and the CB JoomGallery plugin from here. We would like to link the JoomGallery author`s name to their CB profile. Is there any plugin that can do this? If not, what would we need to 'hack' to get this modification? We would like the Author link to show in all the different JoomGallery layouts as well as in the JoomImage module.

Thank you.

**Comment by pepperstreet** [comment]
Good point. Just know of the following JG v2 J!2.5 plugin
http://www.en.joomgallery.net/downloads/joomgallery-for-joomla-25/plugins/joomdisplaycbname.html

Maybe it is still usable and compatible!?

**Comment by line49** [comment]
Hi,

Unfortunately, it doesn't work on a Joomla 3 site with JoomGallery 3.1.1. You get the following errors:
Warning: Parameter 1 to plgJoomGalleryJoomDisplayCBName::onJoomDisplayUser() expected to be a reference, value given in /home/username/public_html/libraries/joomla/event/event.php on line 71

Thank you for the suggestion.

I actually have hacked /administrator/components/com_joomgallery/helpers/html/joomgallery.php and added line 99:
$username_cb = $user->get('username'); // Hack to get username for CB profile link below
and then changed line 110: return $username;
to:
return '<a href="/component/comprofiler/userprofile/'.$username_cb.'/">'.$username.'</a>'; // Hack to add link to CB profile to author's name

which works. But would be better to have a plugin rather than having to hack core code.

**Comment by pepperstreet** [comment]
@line49 
Thanks for testing and the (negative) confirmation. Good to know. Thanks for the "hack" info as well.

I did not use JG for quite some time. So, i had no personal experience with v3. Especially with missing plugins and integrations. Hope they will get an update soon.

**Comment by Chraneco** [comment]
Hi,
you could solve that problem in the plugin by removing the & sign in line 70 of file 'plugins/joomgallery/joomdisplaycbname/joomdisplaycbname.php'

**Comment by Chraneco** [comment]
An updated version of the display name plugin has been released for Joomla! 3.x:
https://github.com/JoomGallery/JoomDisplayCBname/releases
